# Generated by Django 5.2.15 on 2026-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("community_invite", "Community Invite"),
                    ("photo_like", "Photo Like"),
                    ("photo_comment", "Photo Comment"),
                    ("photo_tag", "Photo Tag"),
                ],
                max_length=30,
            ),
        ),
    ]
