# Generated by Django 5.2.15 on 2026-08-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_type"),
        ("stories", "0002_story_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stories.story",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("community_invite", "Community Invite"),
                    ("photo_like", "Photo Like"),
                    ("photo_comment", "Photo Comment"),
                    ("photo_tag", "Photo Tag"),
                    ("story_tag", "Story Tag"),
                ],
                max_length=30,
            ),
        ),
    ]
