version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION}"
        awslogs-group: "photoz-lb-logs"
        awslogs-stream: "nginx-proxy"
        awslogs-create-group: "true"
