# Generated by Django 5.2.16 on 2026-09-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_userprofile_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follower_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
