# Generated by Django 5.2.15 on 2026-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
