# Generated by Django 5.2.15 on 2026-07-05 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0001_initial"),
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["photo", "created_at"], name="idx_comment_photo_created"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["user", "-created_at"], name="idx_photo_user_created"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["community", "-created_at"], name="idx_photo_community_created"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["-created_at"], name="idx_photo_created_at"),
        ),
    ]
