# Generated by Django 5.2.15 on 2026-07-08 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_comment_idx_comment_photo_created_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="photo",
            name="idx_photo_created_at",
        ),
    ]
